### ISSUE TITLE
Console access inefficient

### ISSUE THREAD

**Issue by RmbRT** [Milania1/TestProject_ParallelExecution#1]
The whole console output has to be created by the programmer into a string, which is overkill. If you used my library `Lock`, you could do a static `lock::ThreadSafe<std::ostream*> scout = &std::cout;` in the class and let `write()` return `scout.write()` which returns a write lock on the `std::cout` object (or rather, on its pointer). The user could then use the `std::ostream` interface directly: `**write() << x << " " << y << '\n';` would own `std::cout` for the whole duration of the statement.

**Comment by JanSellner** [comment]
Thanks for pointing out the issue and sorry for the late reply.

Personally, I only use the console writing function for debugging purposes where performance does not really matter so much. But I appreciate that you probably have different use cases.

I like the idea of using the iostreams directly. This makes the printing process syntactically easier to handle. However, adding a new dependency for this issue seems a bit overkill to me (even though your library sound very interesting).

As far as I understand, the basic idea of your lock objects is to create a temporary object when the resource is acquired. This object locks the mutex in the beginning and releases it in the destructor. This way, access to the resource is granted in the current scope of the object.

I implemented this idea for the `ParallelExecution` class by also creating a temporary object which locks the mutex and initiates the console access (and unlocks it in the destructor). Basically, you can now write something like
```cpp
pe.cout() << "Iteration " << i << " done" << std::endl;
```

I pushed the code to the [locked_console_writing](https://github.com/Milania1/TestProject_ParallelExecution/tree/locked_console_writing) branch. If you like, you can give it a try. Note: I use an [`inline` variable](https://stackoverflow.com/questions/38043442/how-do-inline-variables-work) in the implementation of the console mutex, so this requires the latest Visual Studio compiler (with the `/std:c++latest` switch).

**Comment by RmbRT** [comment]
Alright, you got my blessing on this! My final suggestion is that you could add support for locking `std::cerr` as well, so that it would also be possible to write errors properly.

On a side note: You are lacking a synchronisation interface in general: Currently, the user has to use synchronisation using extra variables manually to access shared variables. Since my Lock library is only one header, it would be easy to add, and would provide a relatively easy interface for providing exclusive and shared locks so that the programmer wouldn't have to bother with complicated synchronisation code any more.

But that is only for convenience and not an issue in itself, so I am marking this as closed.

**Comment by JanSellner** [comment]
Ok, advice accepted and implemented :-).

Currently, I am not planning to extend the synchronisation. I think it is ok to let the user pick their own library as they see fit (and end up e.g. with your library).

Thanks again for addressing the issue.
